# Generated by Django 4.1 on 2022-10-05 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('subscribed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date subscribed')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
