# Generated by Django 4.1 on 2022-10-05 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscribedusers_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='subscribedusers',
            name='subscribed_date',
        ),
        migrations.AddField(
            model_name='subscribedusers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
