# Generated by Django 4.1 on 2022-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedusers',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
