# Generated by Django 4.1 on 2022-10-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_subscribedusers_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribedUsers',
            new_name='SubscribedUser',
        ),
    ]
