# Generated by Django 4.1 on 2022-10-06 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_subscribedusers_subscribeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduser',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Subscribed'),
        ),
    ]
