# Generated by Django 4.1.1 on 2022-10-06 22:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_subscribeduser_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank='True', null='True'),
        ),
    ]
